### ISSUE TITLE
Error when using map_op_info with extended data structures

### ISSUE THREAD

**Issue by fc-tdcnet** [pycrate-org/pycrate#16]
Hey! Amazing repo, thanks for the great work!

I've installed the library using `python -m pip install .` and tried to use `pycrate_map_op_info.py`. It works if I don't use the `-x` option, but when I use it I get this error:
```
pycrate_map_op_info.py -o 2 -x

--------------------------------------------------------------------------------
-----------------------  MAP operationCode: (local, 02)  -----------------------
--------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/bin/pycrate_map_op_info.py", line 248, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/bin/pycrate_map_op_info.py", line 243, in main
    print_operation_infos(args)
  File "/usr/local/bin/pycrate_map_op_info.py", line 226, in print_operation_infos
    show_infos(val, args.e, args.x)
  File "/usr/local/bin/pycrate_map_op_info.py", line 126, in show_infos
    get_construct_info(arg, info, wext)
  File "/usr/local/bin/pycrate_map_op_info.py", line 88, in get_construct_info
    c.get_proto(w_open=wext, w_opt=wext, w_enum=wext, blacklist=bl)[1]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ASN1Obj.get_proto() got an unexpected keyword argument 'w_open'
```

**Comment by mitshell** [comment]
Thanks for the report.
I forgot to update this tool after changing the method _get_proto()_ from the ASN.1 RT. the commit https://github.com/pycrate-org/pycrate/commit/2a6ab2e59e66e4946795558632c0218a5fd44022 should have fixed this issue now.

**Comment by fc-tdcnet** [comment]
Thanks for the fix!
